### ISSUE TITLE
Issues Changing Labels and Leaf Colors

### ISSUE THREAD

**Issue by sventura** [talgalili/dendextend#31]
I want to color the leaves of the dendrogram by a vector with the same length of the data, e.g. clustering labels from hierarchical clustering via `cutree()`:

```
library(MASS)
library(dendextend)
library(dplyr)
library(ggplot2)
data(Cars93)
cars_cont <- select(Cars93, Price, MPG.city, MPG.highway, EngineSize, 
                    Horsepower, RPM, Fuel.tank.capacity, Passengers,
                    Length, Wheelbase, Width, Turn.circle, Weight)

hc <- cars_cont %>% scale %>% dist %>% hclust 
dend <- hc %>% as.dendrogram
dend %>% set("labels_colors", cutree(hc, k = 4)) %>% ggplot
```

But the behavior here is not as expected.  That is, the colors of the leaves under a given branch of the dendrogram should all be the same color (corresponding to the four-cluster solution), but they appear to be displayed randomly.

Additionally, setting the leaf labels with a length-n vector does not appear to work properly either.  For example, `dend %>% ggplot` shows that the first three default leaf labels, moving from left to right, are 31, 80, and 42 -- presumably corresponding to rows 31, 80, and 42 in the dataset.

The types of cars for these indices are:  

```
> Cars93$Type[c(31, 80, 42)]
[1] Small Small Small
```

But when setting the labels with the `Type` vector, the appropriate labels do not appear in these positions in the dendrogram.  For example, the labels in the corresponding positions after setting the labels according to the car `Type` are `Small Midsize Compact` using the following code:

```
dend %>% set("labels", Cars93$Type) %>% ggplot
```

**Both of these issues appear to be because the set() function does not take into account the `$order` of the `hclust` object.  When I use the following code, everything works:**

```
dend %>% set("labels_colors", cutree(hc, k = 4)[hc$order]) %>% ggplot
dend %>% set("labels", Cars93$Type[hc$order]) %>% ggplot
```

Is it possible to make it so set() takes into account the `$order` of the `hclust` object, in order to prevent this counterintuitive labeling style?

Also, after reading through the documentation, it's not immediately obvious if the `order.hclust()` or `order.dendrogram()` functions attempt to fix these issues already.  Is it possible that could you update the documentation here with some examples of the interplay of these functions and `set()`?  (Or did I miss an example?)

Thanks!

-SV

**Comment by jefferis** [comment]
There's some discussion that I think is related in #18 but unfortunately progress on that stagnated because I have been very busy with new projects and the right solution is a little fiddly. As it happens there are some functions in the dendroextras package that provide the option to return in dendrogram order (slice, subset) and it would be great to fold that functionality into dendextend, which is much more comprehensive and mature package.

**Comment by talgalili** [comment]
Dear @sventura 

Several things - 
1) If you wanted to have the 4 clusters colors, you could have used (for example) `color_labels`. For example: `dend %>% color_labels(k = 4) %>% plot`. 
To get the same result with set("labels_colors",...) use the following:
```r
dend %>% set("labels_colors", cutree(hc, k = 4)[order.hclust(hc)]) %>% plot
```
To get:
![image](https://cloud.githubusercontent.com/assets/976006/19919427/673276ea-a0db-11e6-8f0f-909947c4823d.png)

I believe this should be the default behavior (using the order of the labels and not that of the data). But in order to help with this, I just pushed to github a new version of dendextend. In this version, the set function now has a new parameter with the name "order_value" that would make the following two calls give the same output:

```r
dend %>%set("labels_colors", cutree(hc, k = 4)[order.hclust(hc)]) %>% plot
dend %>% set("labels_colors", cutree(hc, k = 4), order_value = TRUE) %>% plot
```

Does this solve the issue you raised here?

Cheers,
Tal


Cheers,
Tal

**Comment by sventura** [comment]
Tal,

Yes, this is fantastic -- thanks!

Also, thanks for the note on `color_labels()` -- I know that this exists, but I was just trying to give a trivial example of where the previous version wasn't behaving as I had expected when inputting a length-n vector in `set()`.  I'm mainly interested in coloring the leaves by some categorical variable from the original dataset, e.g. `Cars93$Type`.

Thanks again for the quick response and easy solution!

-SV

**Comment by talgalili** [comment]
My pleasure @sventura 

Cheers,
Tal
