### ISSUE TITLE
cutree returns all zero vector

### ISSUE THREAD

**Issue by grafab** [talgalili/dendextend#5]
I ran into problems with cutree, when I had a tree with zero distance leafs.
Here is a minimal example that reproduces the problem:
> dend<-as.dendrogram(hclust(dist(c(1,1,1,2,2))))
> cutree(dend,k=5)
> [1] 0 0 0 0 0

I expected the result to be:
> cutree(hclust(dist(c(1,1,1,2,2))),k=5)
> [1] 1 2 3 4 5

I figured out that it has to do with the function `heights_per_k.dendrogram`.
It results in negative values for h:

> heights_per_k.dendrogram(dend)
>    1    2    0 
>  1.5  0.5 -0.5

Negative height reproduced the results, that I got before:
> cutree(dend,h=-0.5)
> [1] 0 0 0 0 0

**Comment by talgalili** [comment]
Hi grafab,
Thank you for the report.
What do you think should be the output for:
cutree(dend,k=3)
?
(I'm asking since I am not sure which definitions to give to such a situation...)

I will also look at what you report and fix it around next week.

Thanks again :)
Tal

**Comment by grafab** [comment]
I think you have three options here:
1. Give an error, like for k=6.
2. Return the result of the highest possible k. In the example k=2.
3. Split up one of the groups as it happens for hclust objects:

> cutree(hclust(dist(c(1,1,1,2,2))),k=3)
> [1] 1 1 1 2 3

The last one would be consistent with stats:cutree. However, I would appreciate a warning, because the result differs, if the orientation of the input changes:
> cutree(hclust(dist(c(2,2,1,1,1))),k=3)
> [1] 1 1 2 2 3

**Comment by talgalili** [comment]
Hi grafab,
I looked into this more. In general, hclust does not really "like" this type of situation (they want only ultrametric trees). So if you'd try to do:

```r
dend <- as.dendrogram(hclust(dist(c(1,1,1,2,2))))
as.hclust(dend)
```
It will give you an error: 
Error: all(vapply(s, is.integer, NA)) is not TRUE

So I think the behavior of stats::cutree in this case is not (IMHO) the best design choice.
Since these results would later be used for comparing trees, I fear the case that people would use these pseudo clusters for inference, and would rather they get a vector of 0's to indicate that their request is not meaningful for that given k and have them rethink their strategy.

Per your suggestion I did add a warning when such a case occurs.

With regards,
Tal
