### ISSUE TITLE
Issue with installing Dendextend

### ISSUE THREAD

**Issue by Mshoukat1992** [talgalili/dendextend#78]
Hi,

I recently encountered an issue with dendextend which I have historically been using with no issues.
When I call the library (library(dendextend)) in bash I get an error following which I uninstalled and reinstalled dendextend which now no longer installs.

I get the following error on installation using
install.packages("dendextend")

Error:

Error in dyn.load(file, DLLpath = DLLpath, ...) :
unable to load shared object '/usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so':
dlopen(/usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
Referenced from: /usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so
Reason: image not found
ERROR: lazy loading failed for package ‘dendextend’

removing ‘/usr/local/lib/R/3.5/site-library/dendextend’
The downloaded source packages are in
‘/private/var/folders/tw/fgxg7p2x1v14h9n_29dv64th0000gn/T/RtmpLoHIjI/downloaded_packages’
Warning message:
In install.packages("dendextend") :
installation of package ‘dendextend’ had non-zero exit status

I am using the most up to date version of R 1.1.4

Any thoughts on what might be going on here

**Comment by talgalili** [comment]
Very odd.

Could you please try restarting R, install dendextend, and paste the
output. Plus also the output of sessionInfo()
?

**Comment by Mshoukat1992** [comment]
I re-ran it and got the same error

> install.packages('dendextend')
Installing package into ‘/usr/local/lib/R/3.5/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/dendextend_1.8.0.tar.gz'
Content type 'application/x-gzip' length 1758392 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

* installing *source* package ‘dendextend’ ...
** package ‘dendextend’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so':
  dlopen(/usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib
  Referenced from: /usr/local/lib/R/3.5/site-library/mclust/libs/mclust.so
  Reason: image not found
ERROR: lazy loading failed for package ‘dendextend’
* removing ‘/usr/local/lib/R/3.5/site-library/dendextend’
Warning in install.packages :
  installation of package ‘dendextend’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/tw/fgxg7p2x1v14h9n_29dv64th0000gn/T/Rtmp2snGck/downloaded_packages’
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin17.5.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0

**Comment by talgalili** [comment]
Mmm
Do you by chance have an older version of R? If so, could you try to repeat
the process and see if it works there or not?

**Comment by talgalili** [comment]
Could you please try running:
install.packages("mclust")
install.packages("dendextend")

If that doesn't work, please try:

install.packages.2 <- function (pkg) if (!require(pkg)) install.packages(pkg);
install.packages.2('devtools')
# install.packages.2('Rcpp')
# make sure you have Rtools installed first! if not, then run:
#install.packages('installr'); install.Rtools()
devtools::install_github('talgalili/dendextend')


Does any of the two work?

**Comment by Pirshtuk** [comment]
Shiny application failed because of error in package installation.

**To Reproduce**
A) press Run App
> ### install.packages("denextend")
library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
there is no package called 'denextend'

B) Or run several times from console
>install.packages("denextend")
one of them fails same way.

**Expected behavior**
I expecte no loading of the packages, as it is installed.


**Additional context**
>sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13        magrittr_2.0.1         usethis_2.0.1          devtools_2.4.1        
 [5] pkgload_1.2.1          R6_2.5.0               rlang_0.4.11           fastmap_1.1.0         
 [9] tools_4.0.5            pkgbuild_1.2.0         DT_0.18.1              sessioninfo_1.1.1     
[13] cli_2.5.0              withr_2.4.2            htmltools_0.5.1.1      ellipsis_0.3.2        
[17] remotes_2.3.0          digest_0.6.27          rprojroot_2.0.2        lifecycle_1.0.0       
[21] crayon_1.4.1           processx_3.5.2         purrr_0.3.4            callr_3.7.0           
[25] htmlwidgets_1.5.3.9000 fs_1.5.0               ps_1.6.0               curl_4.3.1            
[29] testthat_3.0.2         glue_1.4.2             memoise_2.0.0          cachem_1.0.5          
[33] compiler_4.0.5         desc_1.3.0             prettyunits_1.1.1

**Comment by Pirshtuk** [comment]
When I publish Shiny App to my shinyapp.io account, I get error and process stops. 

Preparing to deploy application...DONE
Uploading bundle for application:  Unable to retrieve package records for the following packages:
- "denextend"...
  Package 'denextend' not available in repository or locally

**Comment by talgalili** [comment]
It says denextend
Instead of dendextend
